In [1]:
import pandas as pd

In [2]:
df_eMol = pd.read_csv("Quote-Cart_searched_with_isoSMILES_tier1_100mg.csv")
df_eMol.head()

,eMolecules_Order_Number,NAME,PO_Number,ORIG_ROWNUM,MATCH_TYPE,MWT,SMILES,SUPPLIER_NAME,CATALOG_NUMBER,SHIPPED_AMOUNT,SHIPPED_UNITS,BARCODE,PLATE_BARCODE,LOCATION,Text 1,EMOLECULES_ID
0,350033304,Mehtap Isik,NaN,1,exact,237.26,c1ccc(cc1)Nc1nnc(o1)c1ccccc1,Enamine Screening Compounds,Z223448766,NaN,mg,NaN,NaN,NaN,NaN,37308
1,350033304,Mehtap Isik,NaN,2,exact,270.24,Oc1ccc(cc1)c1cc(=O)c2c(o1)cc(cc2O)O,Vitas M Labs,STK801630,NaN,mg,NaN,NaN,NaN,NaN,478202
2,350033304,Mehtap Isik,NaN,3,exact,130.15,c1ccc2c(c1)ncnc2,Maybridge,AC15398,NaN,mg,NaN,NaN,NaN,NaN,479644
3,350033304,Mehtap Isik,NaN,4,exact,76.12,NC(=S)N,Vitas M Labs,STL194300,NaN,mg,NaN,NaN,NaN,NaN,484431
4,350033304,Mehtap Isik,NaN,5,exact,234.20,COc1ccc2c(c1)oc(=O)cc2CC(=O)O,Enamine Screening Compounds,Z276516410,NaN,mg,NaN,NaN,NaN,NaN,490595

In [3]:
df_frag = pd.read_csv("df_frag_final.csv")
df_frag.head()

,eMolecules ID,canonical isomeric SMILES,eMolecules SMILES,"pKas in [3,11]",XlogP,MolWt,Availability (mg),Price,group,N_Rot,N_UV_chrom,Selection,Bin index,Priority,Final list
0,6679830,c1cc2c(cc1O)c3c(o2)C(=O)NCCC3,Oc1cc2c3CCCNC(=O)c3oc2cc1,[9.119],0.720,217.221,184.0,533.0,fragment-like,0,27,picked,4,1,True
1,719540,c1ccc(cc1)n2c3c(cn2)c(ncn3)N,Nc1ncnc2c1cnn2c1ccccc1,[3.869],1.499,211.223,3430.0,414.0,fragment-like,1,31,picked,8,1,True
2,37095168,c1ccc2c(c1)ncn2c3ccc(cc3)O,Oc1ccc(cc1)n1cnc2c1cccc2,"[5.82, 8.709]",2.219,210.231,21650.2,148.0,fragment-like,1,40,picked,11,1,True
3,37053191,c1ccc(cc1)c2[nH]c3ccc(cc3n2)C(=O)N,NC(=O)c1ccc2c(c1)nc([nH]2)c1ccccc1,[6.342],2.192,237.257,2000.0,168.0,fragment-like,2,42,picked,11,2,True
4,31653344,c1ccc(cc1)n2cnc3c2ccc(c3)N,Nc1ccc2c(c1)ncn2c1ccccc1,[6.348],2.333,209.247,50213.0,148.0,fragment-like,1,40,picked,12,1,True

In [4]:
df_frag["Supplier Name"] = None
df_frag["Catalog Number"] = None

for i, row in df_frag.iterrows():
    eMolecules_ID = row["eMolecules ID"]
    
    # Supplier
    supplier = df_eMol.loc[df_eMol["EMOLECULES_ID"] == eMolecules_ID]["SUPPLIER_NAME"]
    supplier = str(supplier.values[0])
    df_frag.loc[i, "Supplier Name"] = supplier
    
    # Catalog number
    cat_number = df_eMol.loc[df_eMol["EMOLECULES_ID"] == eMolecules_ID]["CATALOG_NUMBER"]
    cat_number = str(cat_number.values[0])
    df_frag.loc[i, "Catalog Number"] = cat_number
    
# Sort by supplier
df_frag = df_frag.sort_values("Supplier Name")

In [5]:
df_frag.to_csv("df_frag_final_supplier.csv")